const actions = {
    LOGIN_SUCCESS :     'LOGIN_SUCCESS',
    LOGIN_FAILED :      'LOGIN_FAILED',
    LOGIN_FATALERROR :  'LOGIN_FATALERROR',

    LOGOUT_SUCCESS :    'LOGOUT_SUCCESS',
    LOGOUT_FAILED :     'LOGOUT_FAILED',
    LOGOUT_FATALERROR : 'LOGOUT_FATALERROR',

    GET_PROFILE_SUCCESS :   'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED :    'GET_PROFILE_FAILED',

    UPDATE_PROFILE_SUCCESS :'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILED  :'UPDATE_PROFILE_FAIELD',


}

export default actions